export { fileSystem } from './fileSystem'
export { vaultService } from './vault'
export type { VaultBackend, VaultBridge, VaultService, VaultState } from './vault'
export { aiService, FetchAIProvider, configureAIProvider, ensureDefaultProvider } from './ai'
export type { AIProvider, AIOptions } from './ai'
export type { ChatMessage, AIConfig } from '@/types'
export { extractTextFromImage, imageToBase64, terminateOCR } from './ocr'
export { extractTextFromPDF } from './pdf'
export { ragService } from './rag'
export { versionHistory } from './versionHistory'
export type { Snapshot } from './versionHistory'
export { knowledgeIndex } from './knowledgeIndex'
export type { KnowledgeIndexRecord, KnowledgeReference } from './knowledgeIndex'
export { createMissingHeadingsAndBlocksFromAuditReport, createMissingNotesFromAuditReport, runMigrationAudit } from './migrationAudit'
export type { MigrationAuditIssue, MigrationAuditIssueType, MigrationAuditRepairResult, MigrationAuditReport, MigrationAuditSyntax } from './migrationAudit'
export { rssService } from './rss'
export type { RSSFeed, RSSArticle, RSSImportOptions, RSSFetchResult } from '@/types'
